### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by VKdeveloper** [ankuryadav7/FusedBulb#4]
When i tried using your library in Android 10 ,

Following error is generated in log:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzaa;
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source:2)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:0)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7024)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6569)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6464)
        at android.app.ActivityThread.access$1300(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzaa" on path: DexPathList[[zip file "/data/app/com.infoteksoftware.ble-qz_c-w9JTCSwfyWzzsR8ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.infoteksoftware.ble-qz_c-w9JTCSwfyWzzsR8ug==/lib/arm64, /data/app/com.infoteksoftware.ble-qz_c-w9JTCSwfyWzzsR8ug==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source:2) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:0) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7024) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6569) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6464) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:220) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) `

When i removed your library, everything works fine.

Is it something to do with your old version of gms ?

**Comment by VKdeveloper** [comment]
I have downloaded your code and done all the necessary changes, there is also small typo in the code.
After doing all the changes. Library gave no errors.
